language: php
php:
 - '7.4'

sudo: false

cache:
 directories:
  - $HOME/.composer/cache
  - .cache

stages:
 - test

jobs:
 include:
  - stage: test
    name: "Test latest"
    before_script:
     - composer update --prefer-dist --no-ansi --no-interaction --no-progress
    script:
     - composer ci-all
  - stage: test
    name: "Test lowest"
    before_script:
     - composer update --prefer-dist --no-ansi --no-interaction --no-progress --prefer-lowest
    script:
     - composer ci-all