name: Draft Release
on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'

jobs:
  draft_release:
    name: Create draft release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: draft release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
